version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
    - mongodb-data:/data/db
    networks:
    - mongodb-network
    ports:
    - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
    - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    volumes:
    - mongodb-data:/data/db
    networks:
    - mongodb-network
    depends_on:
    - mongodb
    ports:
    - 8081:8081
    restart: unless-stopped

volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongodb-network:
    name: mongodb-network
